# Numpy
Numpy é uma biblioteca de álgebra linear para a linguagem Python, a razão que numpy é tão importante para o minicurso é a intensa utilização da formulação matricial para o desenvolvimento da teoria e da aplicação em redes neurais. <br>
Outro motivo é que Numpy é extremamente rápido, a biblioteca possui vinculação com a linguagem C e isto a torna uma excelente escolha para a implementações que exigem eficiência em cálculo numérico.

## Instruções de instalação
Após a instalação do gerenciador de pacotes Anaconda, por padrão, a biblioteca Numpy será instalada automaticamente. 
Caso você tenha feito modificações no momento da instalação, deverá utilizar o comando <br>
<span style="display:inline-block; width: 10px;"></span>    `conda install numpy`

## Usando Numpy
Uma vez instalado, você pode importar a biblioteca usando:

In [1]:
import numpy as np

Numpy possui diversas funções e implementações úteis, entre elas: arrays, vetores, matrizes e geração de números. Uma array pode ser um vetor ou uma matriz.

# 1. Arrays usando Numpy 

## 1.1. Criando arrays

## A partir de uma lista em Python
Pode-se criar uma array em Numpy a partir da conversão direta de uma lista em python, ou uma lista de uma lista (matriz).

In [2]:
lista = [1,2,3]
lista

[1, 2, 3]

In [3]:
np.array(lista)

array([1, 2, 3])

In [4]:
matriz = [[1,0,0],[0,1,0],[0,0,1]]
matriz

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [8]:
np.array(matriz)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Métodos úteis
Existem diversos métodos que facilitam a criação de arrays já inclusos na biblioteca Numpy.

#### arange
Retorna valores igualmente espaçados para um dado intervalo.

In [9]:
# Por default, o espaçamento padrão é de valor 1
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# Podemos selecionar o valor do espaçamento
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

### zeros e ones
Retornam arrays compostas apenas de zeros ou de uns.

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

### linspace
Retorna uma certa quantia de valores igualmente espaçados em um dado intervalo.

In [19]:
np.linspace(0,25,51)

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,
        13.5,  14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,
        18. ,  18.5,  19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,
        22.5,  23. ,  23.5,  24. ,  24.5,  25. ])

### eye

Retorna matrizes identidades dado uma dimensão

In [22]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

### Arrays com números aleatórios

### Random
O método random fornece várias maneiras de gerar arrays com números aleatórios.

In [40]:
# Vamos importar a biblioteca matplotlib para visualizar a diferença entre as distribuições 
# de números aleatórios fornecidas pelo método random.
import matplotlib.pyplot as plt
%matplotlib inline

#### rand
Retorna uma array dado um formato e a preenche com valores aleatórios em uma distribuição uniforme no intervalo [0,1)

In [41]:
array1 = np.random.rand(100)
print(array1)
plt.hist(array1, normed=True, bins=10)

[ 0.08138805  0.76015561  0.7764734   0.78031851  0.22360456  0.710799
  0.54218462  0.40066694  0.48699595  0.96455068  0.21686624  0.54043873
  0.79774719  0.20884704  0.96861498  0.19437299  0.57131256  0.40160656
  0.50331698  0.62034383  0.03097027  0.70986086  0.56384622  0.22284874
  0.41659996  0.5438471   0.4614624   0.56888625  0.7113504   0.8095915
  0.33200039  0.94390805  0.18936114  0.09957109  0.06622681  0.36278664
  0.62226677  0.3760823   0.35025912  0.5644496   0.71387153  0.17036213
  0.34779493  0.17469971  0.31339307  0.41728112  0.77892582  0.82435169
  0.71777965  0.01153054  0.93810244  0.60488185  0.45425325  0.99043387
  0.66252269  0.17029895  0.01322213  0.44519751  0.79486789  0.7327071
  0.79915252  0.40949669  0.9319528   0.34883679  0.53867501  0.1493746
  0.06539524  0.76997251  0.53739256  0.51862324  0.26573752  0.81304028
  0.61133086  0.50426018  0.37946467  0.07369031  0.57574132  0.11941334
  0.34488106  0.41730794  0.06965487  0.31499138  0.2413

(array([ 1.2258616 ,  0.81724107,  1.02155133,  1.2258616 ,  0.9193962 ,
         1.32801673,  0.71508593,  1.32801673,  0.81724107,  0.81724107]),
 array([ 0.01153054,  0.10942088,  0.20731121,  0.30520154,  0.40309188,
         0.50098221,  0.59887254,  0.69676287,  0.79465321,  0.89254354,
         0.99043387]),
 <a list of 10 Patch objects>)

#### randn
Retorna uma array dado um formato e a preenche com valores aleatórios em uma distribuição norma no intervalo [0,1)

In [42]:
array2 = np.random.randn(100)
print(array2)
plt.hist(array2, normed=True, bins=10)

[-0.00600327  0.38213203 -0.48027713  0.54275141 -1.43752039  0.59166992
  1.44291868  0.82219536  2.50240812 -1.84895414  0.46695939  0.36249283
  0.83646168 -1.15173754  1.02515487  1.08845094  0.08042657  0.2146388
 -0.73033966  0.39281675  0.01789784 -0.51851316  0.33052153 -0.18590698
  0.50102922  2.30241584  0.55703464 -0.3395867  -0.04617742  0.0785581
 -0.15839662 -0.37700112 -0.29296528  1.32535664 -0.41997855  1.3878434
 -0.93332129  1.1127876  -0.11208499  0.29504116  0.33854551 -0.4699727
  0.27095237 -0.15839796  0.16077515  1.46122952  0.63218318  1.82815682
  1.05204858  0.45976046 -1.01345749 -0.98677661 -0.41024908  1.03970913
 -1.13229306  1.51187218 -2.31305074  1.3703934  -0.57890043  0.02380811
  0.39421296  0.10549388 -2.25069449 -0.46336475 -1.97184812  0.26098324
 -0.49517032 -0.0851212   0.4347165  -0.44041525  0.633785    0.45553137
  0.54871382 -1.15617491  0.26482301 -1.24402647  0.32540644  0.83585629
  0.81411548  2.30113306 -0.66533316 -1.42313953  0.362

(array([ 0.08306581,  0.06229936,  0.20766453,  0.29073034,  0.33226325,
         0.49839487,  0.3530297 ,  0.16613162,  0.02076645,  0.06229936]),
 array([-2.31305074, -1.83150485, -1.34995897, -0.86841308, -0.3868672 ,
         0.09467869,  0.57622457,  1.05777046,  1.53931635,  2.02086223,
         2.50240812]),
 <a list of 10 Patch objects>)

#### randint
Retorna números inteiros aleatórios a partir de um intervalo [a,b), ou seja, não inclui o valor superior.

In [43]:
np.random.randint(1,10)

6

In [44]:
np.random.randint(1,100,5)

array([86, 12,  6, 45, 51])

## 1.2 Métodos e atributos de arrays em Numpy